# Generated by Django 5.1.15 on 2026-09-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='是否暂停'),
        ),
    ]
